print("Input")
nama = input("Nama                        : ")
nim = input("NIM                         : ")
kelas_paralel = input("Kelas Paralel               : ")
tempat_lahir = input("Tempat/Tanggal Lahir        : ")
alamat = input("Alamat                      : ")
hobi = input("Hobby                       : ")
no_hp = input("No. HP                      : ")

print("\nOutput")
print(f"Nama                        : {nama}")
print(f"NIM                         : {nim}")
print(f"Kelas Paralel               : {kelas_paralel}")
print(f"Tempat/Tanggal Lahir        : {tempat_lahir}")
print(f"Alamat                      : {alamat}")
print(f"Hobby                       : {hobi}")
print(f"No. HP                      : {no_hp}")
